# Configuration for Nginx Proxy Manager
# MIT License (c) 2024 Jack Perry

services:
  # Nginx Proxy Manager
  app:
    container_name: "${APP_NAME:-app}-nginx-proxy-manager"
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80" # Public HTTP Port
      - "${HTTPS_PORT:-443}:443" # Public HTTPS Port
      - "${ADMIN_PORT:-81}:81" # Admin Web Port
    environment:
      # MariaDB connection parameters:
      DB_MYSQL_HOST: "${DB_MYSQL_HOST:-db}"
      DB_MYSQL_PORT: "${DB_MYSQL_PORT:-3306}"
      DB_MYSQL_USER: "${DB_MYSQL_USER:-npm}"
      DB_MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD:-npm}"
      DB_MYSQL_NAME: "${DB_MYSQL_NAME:-npm}"

      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      nginx-proxy-manager:
        ipv4_address: ${APP_IP:-172.19.0.2}

  # MariaDB Instance
  db:
    container_name: "${DB_NAME:-db}-nginx-proxy-manager"
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      # Fill out these details in .env!
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_PASSWORD:-npm}"
      MYSQL_DATABASE: "${DB_MYSQL_NAME:-npm}"
      MYSQL_USER: "${DB_MYSQL_USER:-npm}"
      MYSQL_PASSWORD: "${DB_MYSQL_PASSWORD:-npm}"
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      nginx-proxy-manager:
        ipv4_address: ${DB_IP:-172.19.0.3}

networks:
  nginx-proxy-manager:
    ipam:
      config:
        - subnet: "${NETWORK_SUBNET:-172.19.0.0/16}"
